
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mert Atay
 */
public class KullaniciEkle extends javax.swing.JFrame {

    /**
     * Creates new form KullaniciEkle
     */
    public KullaniciEkle() {
        initComponents();
    }
    Object[] secilen_turler = new String[3];
    Object [] satirlar = new Object[3];
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        netflix_icon_1 = new javax.swing.JLabel();
        cumle1 = new javax.swing.JLabel();
        cumle2 = new javax.swing.JLabel();
        cumle3 = new javax.swing.JLabel();
        txt_kullanici_adin = new javax.swing.JLabel();
        txt_kullanici_adi1 = new javax.swing.JTextField();
        sifren = new javax.swing.JLabel();
        txt_password1 = new javax.swing.JPasswordField();
        emailadresin = new javax.swing.JLabel();
        txt_emailadres = new javax.swing.JTextField();
        dogum_tarihin = new javax.swing.JLabel();
        txt_dogumtarihi = new javax.swing.JTextField();
        kayıtol_butonu = new javax.swing.JButton();
        combobox_1 = new javax.swing.JComboBox<>();
        combobox_2 = new javax.swing.JComboBox<>();
        combobox_3 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        listelebutonu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        oneri_tablo = new javax.swing.JTable();
        kullaniciekle_arkaplan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kayıt Ol - Netflix");
        setLocation(new java.awt.Point(300, 100));
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));

        jPanel1.setLayout(null);

        netflix_icon_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/netflix-icon_144x144.png"))); // NOI18N
        jPanel1.add(netflix_icon_1);
        netflix_icon_1.setBounds(50, 30, 144, 150);

        cumle1.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        cumle1.setText("Bizde neden ekli degilsin! Aaa,bak kızarım simdi!");
        jPanel1.add(cumle1);
        cumle1.setBounds(220, 60, 490, 30);

        cumle2.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        cumle2.setText("Gel seni de dünyamıza ekleyelim. Ne dersin?");
        jPanel1.add(cumle2);
        cumle2.setBounds(240, 90, 450, 30);

        cumle3.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        cumle3.setText("Hadi gel, gel!");
        jPanel1.add(cumle3);
        cumle3.setBounds(370, 120, 130, 30);

        txt_kullanici_adin.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        txt_kullanici_adin.setForeground(new java.awt.Color(255, 255, 255));
        txt_kullanici_adin.setText("Kullanıcı Adın:");
        jPanel1.add(txt_kullanici_adin);
        txt_kullanici_adin.setBounds(60, 190, 90, 30);
        jPanel1.add(txt_kullanici_adi1);
        txt_kullanici_adi1.setBounds(60, 220, 120, 20);

        sifren.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        sifren.setForeground(new java.awt.Color(255, 255, 255));
        sifren.setText("Sifren:");
        jPanel1.add(sifren);
        sifren.setBounds(60, 250, 80, 20);
        jPanel1.add(txt_password1);
        txt_password1.setBounds(60, 280, 120, 20);

        emailadresin.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        emailadresin.setForeground(new java.awt.Color(255, 255, 255));
        emailadresin.setText("E-mail Adresin:");
        jPanel1.add(emailadresin);
        emailadresin.setBounds(60, 310, 90, 20);
        jPanel1.add(txt_emailadres);
        txt_emailadres.setBounds(60, 340, 260, 20);

        dogum_tarihin.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        dogum_tarihin.setForeground(new java.awt.Color(255, 255, 255));
        dogum_tarihin.setText("Dogum Tarihin:");
        jPanel1.add(dogum_tarihin);
        dogum_tarihin.setBounds(60, 370, 100, 20);
        jPanel1.add(txt_dogumtarihi);
        txt_dogumtarihi.setBounds(60, 400, 130, 20);

        kayıtol_butonu.setText("Kayıt Ol");
        kayıtol_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kayıtol_butonuActionPerformed(evt);
            }
        });
        jPanel1.add(kayıtol_butonu);
        kayıtol_butonu.setBounds(630, 440, 100, 23);

        combobox_1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aksiyon ve Macera", "Anime", "Belgesel", "Bilim Kurgu ve Fantastik Yapımlar", "Bilim ve Doğa", "Çocuk ve Aile", "Drama", "Gerilim", "Komedi", "Korku", "Reality Program", "Romantik" }));
        combobox_1.setToolTipText("");
        combobox_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox_1ActionPerformed(evt);
            }
        });
        jPanel1.add(combobox_1);
        combobox_1.setBounds(520, 190, 140, 20);

        combobox_2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aksiyon ve Macera", "Anime", "Belgesel", "Bilim Kurgu ve Fantastik Yapımlar", "Bilim ve Doğa", "Çocuk ve Aile", "Drama", "Gerilim", "Komedi", "Korku", "Reality Program", "Romantik" }));
        combobox_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox_2ActionPerformed(evt);
            }
        });
        jPanel1.add(combobox_2);
        combobox_2.setBounds(520, 220, 140, 20);

        combobox_3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aksiyon ve Macera", "Anime", "Belgesel", "Bilim Kurgu ve Fantastik Yapımlar", "Bilim ve Doğa", "Çocuk ve Aile", "Drama", "Gerilim", "Komedi", "Korku", "Reality Program", "Romantik" }));
        combobox_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox_3ActionPerformed(evt);
            }
        });
        jPanel1.add(combobox_3);
        combobox_3.setBounds(520, 250, 140, 20);

        jLabel1.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("En Sevdigin 3 Program Türü:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(420, 160, 230, 20);

        listelebutonu.setText("Listele");
        listelebutonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listelebutonuActionPerformed(evt);
            }
        });
        jPanel1.add(listelebutonu);
        listelebutonu.setBounds(700, 220, 80, 23);

        oneri_tablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Program Adı", "Türü", "Puan Değeri"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(oneri_tablo);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(420, 290, 310, 140);

        kullaniciekle_arkaplan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/black-and-white-photo-of-the-ocean-4100767_800x500.jpg"))); // NOI18N
        jPanel1.add(kullaniciekle_arkaplan);
        kullaniciekle_arkaplan.setBounds(-6, -6, 810, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kayıtol_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kayıtol_butonuActionPerformed
        // TODO add your handling code here:
        String sql_sorgu2;
        int sayac=0;
        sql_sorgu2="SELECT kullanici_id FROM kullanici";
        ResultSet myRs = Baglanti.sorgulama(sql_sorgu2);
        
        try {
            while(myRs.next()){
                sayac++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(KullaniciEkle.class.getName()).log(Level.SEVERE, null, ex);
        }
        //System.out.println("sayac:" + sayac);
        
        int kullanici_id=sayac+1;
        String kullanici_ad = txt_kullanici_adi1.getText();
        String sifre = txt_password1.getText();
        String dogum_tarihi = txt_dogumtarihi.getText();
        String email_adres = txt_emailadres.getText();
        String sql_sorgu1;
        
        sql_sorgu1 ="INSERT INTO kullanici(kullanici_id,kullanici_ad,kullanici_email,kullanici_sifre,kullanici_dtarihi) VALUES ('"+ kullanici_id +"' , '"
                + kullanici_ad + "' , '" + email_adres + "' , '" + sifre + "' , '" + dogum_tarihi +"')";
        
        //System.out.println(sql_sorgu1);
        Baglanti.kayit_ekle(sql_sorgu1);
        //-------------------------------------------------------------------------------------
        
        
        
        //-------------------------------------------------------------------------------------
        String sql_sorgu3;
        ResultSet result;
        result = null;
        boolean kontrol =false;
        sql_sorgu3 ="SELECT * FROM kullanici WHERE kullanici_ad = '" + kullanici_ad + "' AND kullanici_sifre = '" + 
                sifre + "'";
        
        result = Baglanti.sorgulama(sql_sorgu3);
       
        try {
            while(result.next()){
                String k_ad_kontrol=result.getString("kullanici_ad");
                String sifre_kontrol=result.getString("kullanici_sifre");
                
                if(k_ad_kontrol.equals(kullanici_ad) && sifre_kontrol.equals(sifre)){
                    kontrol = true;
                    System.out.println("Kayıt var.");
                }else{
                    kontrol = false;
                }
            }
            if(kontrol == true){
                setVisible(false);
                Uyari uyari = new Uyari();
                uyari.setVisible(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(KullaniciEkle.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }//GEN-LAST:event_kayıtol_butonuActionPerformed

    private void combobox_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox_1ActionPerformed
            secilen_turler[0]=combobox_1.getSelectedItem();
            System.out.println(secilen_turler[0]);
    }//GEN-LAST:event_combobox_1ActionPerformed

    private void combobox_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox_2ActionPerformed
            secilen_turler[1]=combobox_2.getSelectedItem();
            System.out.println(secilen_turler[1]);
    }//GEN-LAST:event_combobox_2ActionPerformed

    private void combobox_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox_3ActionPerformed
            secilen_turler[2]=combobox_3.getSelectedItem();
            System.out.println(secilen_turler[2]);
    }//GEN-LAST:event_combobox_3ActionPerformed

    private void listelebutonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listelebutonuActionPerformed
        try {
            // TODO add your handling code here:
            String sql_sorgu4;
            sql_sorgu4="SELECT DISTINCT program_ad,prog_tur,puan_degeri FROM kullanici_program WHERE prog_tur ='"+secilen_turler[0]
                    +"' OR prog_tur = '" + secilen_turler[1] + "' OR prog_tur = '" + secilen_turler[2] +"' AND puan_degeri > 5";
            ResultSet result;
            result = null;
            
            result = Baglanti.sorgulama(sql_sorgu4);
            int sayac=0;
            while(result.next()){
                 
                 satirlar[0]=result.getString("program_ad");
                 satirlar[1]=result.getString("prog_tur");
                 satirlar[2]=result.getString("puan_degeri");
                 //System.out.println(satirlar[0]);
                 oneri_tablo.setValueAt(satirlar[0], sayac,  0);
                 oneri_tablo.setValueAt(satirlar[1], sayac,  1);
                 oneri_tablo.setValueAt(satirlar[2], sayac,  2);
                 sayac++;
                 oneri_tablo.setVisible(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(KullaniciEkle.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_listelebutonuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KullaniciEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KullaniciEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KullaniciEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KullaniciEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KullaniciEkle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combobox_1;
    private javax.swing.JComboBox<String> combobox_2;
    private javax.swing.JComboBox<String> combobox_3;
    private javax.swing.JLabel cumle1;
    private javax.swing.JLabel cumle2;
    private javax.swing.JLabel cumle3;
    private javax.swing.JLabel dogum_tarihin;
    private javax.swing.JLabel emailadresin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kayıtol_butonu;
    private javax.swing.JLabel kullaniciekle_arkaplan;
    private javax.swing.JButton listelebutonu;
    private javax.swing.JLabel netflix_icon_1;
    private javax.swing.JTable oneri_tablo;
    private javax.swing.JLabel sifren;
    private javax.swing.JTextField txt_dogumtarihi;
    private javax.swing.JTextField txt_emailadres;
    private javax.swing.JTextField txt_kullanici_adi1;
    private javax.swing.JLabel txt_kullanici_adin;
    private javax.swing.JPasswordField txt_password1;
    // End of variables declaration//GEN-END:variables
}
