
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mert Atay
 */
public class KullaniciGirisi extends javax.swing.JFrame {

    /**
     * Creates new form KullaniciGirisi
     */
    public KullaniciGirisi() {
        initComponents();
    }
    public static String kullanici_id;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        netflix_png = new javax.swing.JLabel();
        txt_merhaba = new javax.swing.JLabel();
        txt_hosgeldin = new javax.swing.JLabel();
        txt_kullanici_adin = new javax.swing.JLabel();
        txt_kullanici_adi = new javax.swing.JTextField();
        txt_show_sıfren = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        giris_butonu = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        arkaplan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Netflix");
        setLocation(new java.awt.Point(300, 100));
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));

        jPanel2.setLayout(null);

        netflix_png.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-netflix-240.png"))); // NOI18N
        jPanel2.add(netflix_png);
        netflix_png.setBounds(30, 30, 250, 90);

        txt_merhaba.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        txt_merhaba.setForeground(new java.awt.Color(204, 204, 204));
        txt_merhaba.setText("Merhaba!");
        jPanel2.add(txt_merhaba);
        txt_merhaba.setBounds(690, 220, 100, 30);

        txt_hosgeldin.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        txt_hosgeldin.setForeground(new java.awt.Color(204, 204, 204));
        txt_hosgeldin.setText("Hosgeldin!");
        jPanel2.add(txt_hosgeldin);
        txt_hosgeldin.setBounds(680, 250, 110, 30);

        txt_kullanici_adin.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        txt_kullanici_adin.setForeground(new java.awt.Color(204, 204, 204));
        txt_kullanici_adin.setText("Kullanıcı Adın:");
        jPanel2.add(txt_kullanici_adin);
        txt_kullanici_adin.setBounds(600, 310, 90, 30);

        txt_kullanici_adi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(txt_kullanici_adi);
        txt_kullanici_adi.setBounds(630, 340, 140, 21);

        txt_show_sıfren.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        txt_show_sıfren.setForeground(new java.awt.Color(204, 204, 204));
        txt_show_sıfren.setText("Sıfren:");
        jPanel2.add(txt_show_sıfren);
        txt_show_sıfren.setBounds(600, 370, 80, 20);
        jPanel2.add(txt_password);
        txt_password.setBounds(630, 390, 140, 20);

        giris_butonu.setText("Giriş");
        giris_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giris_butonuActionPerformed(evt);
            }
        });
        jPanel2.add(giris_butonu);
        giris_butonu.setBounds(670, 430, 73, 23);

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel1);
        jPanel1.setBounds(590, 0, 210, 500);

        arkaplan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monochrome-photo-of-people-holding-hands-while-standing-on-4430320_800x500.jpg"))); // NOI18N
        jPanel2.add(arkaplan);
        arkaplan.setBounds(0, 0, 800, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void giris_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giris_butonuActionPerformed
        // TODO add your handling code here:
        kullanici_id= txt_kullanici_adi.getText();
        String sifre= txt_password.getText();
        String sql_sorgu;
        ResultSet myRs1;
        myRs1 = null;
        boolean kontrol = false;
        sql_sorgu="SELECT * FROM kullanici WHERE kullanici_ad ='" + kullanici_id + "' AND kullanici_sifre = '" + sifre +"'";
        
        myRs1=Baglanti.sorgulama(sql_sorgu);
        
        
        
        try {
            while(myRs1.next()){
                String k_ad_kontrol=myRs1.getString("kullanici_ad");
                String sifre_kontrol=myRs1.getString("kullanici_sifre");
                
                if(k_ad_kontrol.equals(kullanici_id) && sifre_kontrol.equals(sifre)){
                    Yonetim yonetim = new Yonetim();
                    yonetim.setVisible(true);
                   // System.out.println("Kayıt var.");
                    setVisible(false);
                }    
            }
           
           
        String sql_sorgu2;
        ResultSet myRs2;
        myRs2=null;
        sql_sorgu2="SELECT kullanici_email FROM kullanici WHERE kullanici_ad = '" + kullanici_id + "'";
        myRs2=Baglanti.sorgulama(sql_sorgu2);
        int sayac=0;
        
        while(myRs2.next()){
            sayac++;
        }
        if(sayac == 0){
            KullaniciEkle k_ekle = new KullaniciEkle();
            k_ekle.setVisible(true);
            setVisible(false);
        }else{
            //System.out.println("kayıt var.");
        }
             
        } catch (SQLException ex) {
            Logger.getLogger(KullaniciGirisi.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
       
    }//GEN-LAST:event_giris_butonuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KullaniciGirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KullaniciGirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KullaniciGirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KullaniciGirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KullaniciGirisi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arkaplan;
    private javax.swing.JButton giris_butonu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel netflix_png;
    private javax.swing.JLabel txt_hosgeldin;
    private javax.swing.JTextField txt_kullanici_adi;
    private javax.swing.JLabel txt_kullanici_adin;
    private javax.swing.JLabel txt_merhaba;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JLabel txt_show_sıfren;
    // End of variables declaration//GEN-END:variables
}
