/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mert Atay
 */
public class Puan_Degeri extends javax.swing.JFrame {

    /**
     * Creates new form Puan_Degeri
     */
    public Puan_Degeri() {
        initComponents();
    }
    public static int puan_degeri;
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        netflix_png = new javax.swing.JLabel();
        yazi_1 = new javax.swing.JLabel();
        yazi_2 = new javax.swing.JLabel();
        txt_puan_degeri = new javax.swing.JTextField();
        Tamam_butonu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Puan_degeriap = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Netflix");
        setLocation(new java.awt.Point(300, 150));
        setMinimumSize(new java.awt.Dimension(400, 300));

        jPanel1.setLayout(null);

        netflix_png.setIcon(new javax.swing.ImageIcon(getClass().getResource("/netflix-icon_128x128.png"))); // NOI18N
        jPanel1.add(netflix_png);
        netflix_png.setBounds(120, 0, 130, 130);

        yazi_1.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        yazi_1.setForeground(new java.awt.Color(255, 255, 255));
        yazi_1.setText("Programımızı izledigin icin tesekkurler.");
        jPanel1.add(yazi_1);
        yazi_1.setBounds(40, 130, 310, 30);

        yazi_2.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        yazi_2.setForeground(new java.awt.Color(255, 255, 255));
        yazi_2.setText("Puanını almak isteriz: (1-10)");
        jPanel1.add(yazi_2);
        yazi_2.setBounds(80, 160, 220, 30);

        txt_puan_degeri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_puan_degeriActionPerformed(evt);
            }
        });
        jPanel1.add(txt_puan_degeri);
        txt_puan_degeri.setBounds(110, 200, 140, 30);

        Tamam_butonu.setText("Tamam");
        Tamam_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tamam_butonuActionPerformed(evt);
            }
        });
        jPanel1.add(Tamam_butonu);
        Tamam_butonu.setBounds(140, 240, 110, 23);

        jLabel1.setText("(Enter'a basın.)");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(254, 204, 100, 20);

        Puan_degeriap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/black-and-white-photo-of-the-ocean-4100767_400x300.jpg"))); // NOI18N
        jPanel1.add(Puan_degeriap);
        Puan_degeriap.setBounds(0, 0, 400, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_puan_degeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_puan_degeriActionPerformed
        // TODO add your handling code here:
        String puan_degeri1= txt_puan_degeri.getText();
        puan_degeri=Integer.parseInt(puan_degeri1);
        System.out.println(puan_degeri);
    }//GEN-LAST:event_txt_puan_degeriActionPerformed

    private void Tamam_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tamam_butonuActionPerformed
        // TODO add your handling code here:
        String kullanici= KullaniciGirisi.kullanici_id;
        String programadi= Yonetim.program_Adi;
        String programturu= Yonetim.program_tur;
        String izleme_tarih= Yonetim.izleme_tarihi;
        int izleme_suresi = Yonetim.izleme_suresi;
        int kaldigi_bolum = Yonetim.kaldigi_bol;
        
        String sql_sorgu2;
           
           sql_sorgu2="INSERT INTO kullanici_program(kullanici_ad,program_ad,prog_tur,izleme_tarihi,izleme_süresi,kaldigi_bolum,puan_degeri)" +
                   "VALUES('" + kullanici + "' , '" + programadi+ "' , '" + programturu + "' , '" + izleme_tarih + "' ," +izleme_suresi +
                   " , " + kaldigi_bolum + " , " + puan_degeri + ")";
            
           Baglanti.kayit_ekle(sql_sorgu2);
           
          setVisible(false);
    }//GEN-LAST:event_Tamam_butonuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Puan_Degeri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Puan_Degeri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Puan_Degeri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Puan_Degeri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Puan_Degeri().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Puan_degeriap;
    private javax.swing.JButton Tamam_butonu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel netflix_png;
    private javax.swing.JTextField txt_puan_degeri;
    private javax.swing.JLabel yazi_1;
    private javax.swing.JLabel yazi_2;
    // End of variables declaration//GEN-END:variables
}
