/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mert Atay
 */
public class Uyari extends javax.swing.JFrame {

    /**
     * Creates new form Uyari
     */
    public Uyari() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        netflix_png = new javax.swing.JLabel();
        yazi1 = new javax.swing.JLabel();
        yazi2 = new javax.swing.JLabel();
        cikis_butonu = new javax.swing.JButton();
        uyari_arkaplan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Uyarı - Netflix");
        setLocation(new java.awt.Point(300, 150));
        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));

        jPanel1.setLayout(null);

        netflix_png.setIcon(new javax.swing.ImageIcon(getClass().getResource("/netflix-icon_128x128.png"))); // NOI18N
        jPanel1.add(netflix_png);
        netflix_png.setBounds(130, 10, 130, 110);

        yazi1.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        yazi1.setForeground(new java.awt.Color(204, 204, 204));
        yazi1.setText("Kaydın Olusturuldu!");
        jPanel1.add(yazi1);
        yazi1.setBounds(90, 130, 220, 40);

        yazi2.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        yazi2.setForeground(new java.awt.Color(204, 204, 204));
        yazi2.setText("Doya Doya Seyret!");
        jPanel1.add(yazi2);
        yazi2.setBounds(100, 160, 200, 40);

        cikis_butonu.setText("Çıkış");
        cikis_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikis_butonuActionPerformed(evt);
            }
        });
        jPanel1.add(cikis_butonu);
        cikis_butonu.setBounds(150, 220, 90, 23);

        uyari_arkaplan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/black-and-white-photo-of-the-ocean-4100767_400x300.jpg"))); // NOI18N
        jPanel1.add(uyari_arkaplan);
        uyari_arkaplan.setBounds(0, 0, 400, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cikis_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikis_butonuActionPerformed
        // TODO add your handling code here:
         System.exit(1);
    }//GEN-LAST:event_cikis_butonuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Uyari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Uyari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Uyari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Uyari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Uyari().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cikis_butonu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel netflix_png;
    private javax.swing.JLabel uyari_arkaplan;
    private javax.swing.JLabel yazi1;
    private javax.swing.JLabel yazi2;
    // End of variables declaration//GEN-END:variables
}
