
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mert Atay
 */
public class Yonetim extends javax.swing.JFrame {

    /**
     * Creates new form Yonetim
     */
    public Yonetim() {
        initComponents();
    }
    Object[] arama_kriteri1 = new Object[1];
    String kullanici = KullaniciGirisi.kullanici_id;
    static String program_Adi;
    static String program_tur;
    static String izleme_tarihi;
    static int izleme_suresi;
    static int kaldigi_bol;
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        netflix_png = new javax.swing.JLabel();
        yazi_hosgeldin = new javax.swing.JLabel();
        arama_kriteri = new javax.swing.JComboBox<>();
        soru = new javax.swing.JLabel();
        yazi2 = new javax.swing.JLabel();
        txt_istenilen_program = new javax.swing.JTextField();
        istenilen_program = new javax.swing.JLabel();
        aranan_tur = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        izlenen_program = new javax.swing.JTextField();
        izlebutonu = new javax.swing.JButton();
        tarih = new javax.swing.JTextField();
        bugun_yazi = new javax.swing.JLabel();
        kaldigi_bolum_yazi = new javax.swing.JLabel();
        txt_kaldigi_bolum = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        program_tablosu = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tur_tablosu = new javax.swing.JTable();
        uyari = new javax.swing.JLabel();
        yonetim_arkaplan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Netflix");
        setLocation(new java.awt.Point(300, 100));
        setMinimumSize(new java.awt.Dimension(800, 500));

        jPanel1.setLayout(null);

        netflix_png.setIcon(new javax.swing.ImageIcon(getClass().getResource("/netflix-icon_128x128.png"))); // NOI18N
        jPanel1.add(netflix_png);
        netflix_png.setBounds(20, 20, 140, 120);

        yazi_hosgeldin.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        yazi_hosgeldin.setForeground(new java.awt.Color(255, 255, 255));
        yazi_hosgeldin.setText("Hosgeldin!");
        jPanel1.add(yazi_hosgeldin);
        yazi_hosgeldin.setBounds(160, 60, 110, 40);

        arama_kriteri.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Program Adı", "Program Türü" }));
        arama_kriteri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arama_kriteriActionPerformed(evt);
            }
        });
        jPanel1.add(arama_kriteri);
        arama_kriteri.setBounds(40, 180, 100, 30);

        soru.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        soru.setForeground(new java.awt.Color(255, 255, 255));
        soru.setText("Hangi arama turunden faydalanmak istersin?");
        jPanel1.add(soru);
        soru.setBounds(20, 150, 260, 20);

        yazi2.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        yazi2.setForeground(new java.awt.Color(255, 255, 255));
        yazi2.setText("Izlemek istedigin program adı:");
        jPanel1.add(yazi2);
        yazi2.setBounds(610, 110, 180, 30);

        txt_istenilen_program.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_istenilen_programActionPerformed(evt);
            }
        });
        jPanel1.add(txt_istenilen_program);
        txt_istenilen_program.setBounds(290, 240, 190, 20);

        istenilen_program.setText("Program tablosundan izlemek istedigin programı gir:(*)");
        jPanel1.add(istenilen_program);
        istenilen_program.setBounds(10, 240, 260, 20);

        aranan_tur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aranan_turActionPerformed(evt);
            }
        });
        jPanel1.add(aranan_tur);
        aranan_tur.setBounds(220, 270, 190, 20);

        jLabel3.setText("Tür tablosundan sevdigin bir türü gir:(*)");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 270, 200, 20);

        izlenen_program.setEditable(false);
        izlenen_program.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        izlenen_program.setOpaque(false);
        jPanel1.add(izlenen_program);
        izlenen_program.setBounds(610, 140, 140, 20);

        izlebutonu.setText("İzle");
        izlebutonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izlebutonuActionPerformed(evt);
            }
        });
        jPanel1.add(izlebutonu);
        izlebutonu.setBounds(640, 390, 90, 20);

        tarih.setEditable(false);
        tarih.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        tarih.setText(new Date().toString());
        tarih.setOpaque(false);
        jPanel1.add(tarih);
        tarih.setBounds(570, 20, 210, 22);

        bugun_yazi.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        bugun_yazi.setForeground(new java.awt.Color(255, 255, 255));
        bugun_yazi.setText("Bugün:");
        jPanel1.add(bugun_yazi);
        bugun_yazi.setBounds(520, 20, 50, 20);

        kaldigi_bolum_yazi.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        kaldigi_bolum_yazi.setForeground(new java.awt.Color(255, 255, 255));
        kaldigi_bolum_yazi.setText("Kaldıgın Bolum:");
        jPanel1.add(kaldigi_bolum_yazi);
        kaldigi_bolum_yazi.setBounds(610, 240, 100, 20);

        txt_kaldigi_bolum.setEditable(false);
        txt_kaldigi_bolum.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        txt_kaldigi_bolum.setOpaque(false);
        jPanel1.add(txt_kaldigi_bolum);
        txt_kaldigi_bolum.setBounds(610, 260, 140, 22);

        program_tablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Program Tablosu"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(program_tablosu);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(160, 310, 270, 170);

        tur_tablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Tür Tablosu"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tur_tablosu);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(20, 310, 130, 170);

        uyari.setForeground(new java.awt.Color(255, 255, 255));
        uyari.setText("* Program ismini ve Tür ismini girerken Enter'a basınız.");
        jPanel1.add(uyari);
        uyari.setBounds(490, 470, 270, 20);

        yonetim_arkaplan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/black-and-white-photo-of-the-ocean-4100767_800x500.jpg"))); // NOI18N
        jPanel1.add(yonetim_arkaplan);
        yonetim_arkaplan.setBounds(0, 0, 800, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void arama_kriteriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arama_kriteriActionPerformed
        // TODO add your handling code here:
         arama_kriteri1[0]=arama_kriteri.getSelectedItem();
         String arama_turu= arama_kriteri1[0].toString();
         //System.out.println(arama_turu);
         
         Object sql_sorgu_satiri;
         String sql_sorgu;
         ResultSet myRs;
         myRs=null;
       
         if(arama_turu.equals("Program Adı")){
             try {
                 sql_sorgu ="SELECT DISTINCT prog_ad FROM program";
                 myRs = Baglanti.sorgulama(sql_sorgu);
                 int sayac=0;
                 while(myRs.next()){
                      sql_sorgu_satiri=myRs.getString("prog_ad");
                      //System.out.println(sql_sorgu_satiri[0]);
                      program_tablosu.setValueAt(sql_sorgu_satiri, sayac, 0);
                      sayac++;
                     
                 }
             } catch (SQLException ex) {
                 Logger.getLogger(Yonetim.class.getName()).log(Level.SEVERE, null, ex);
             }
         }else if(arama_turu.equals("Program Türü")){
             try {
                 String sql_sorgu2 ="SELECT DISTINCT prog_tur FROM program_tur";
                 ResultSet myRs2;
                 myRs2 = null;
                 int sayac2=0;
                 myRs2 = Baglanti.sorgulama(sql_sorgu2);
                 
                 while(myRs2.next()){
                      Object sql_sorgu_cevabi;
                      sql_sorgu_cevabi=myRs2.getString("prog_tur");
                      tur_tablosu.setValueAt(sql_sorgu_cevabi, sayac2, 0);
                      sayac2++;
                 }
             } catch (SQLException ex) {
                 Logger.getLogger(Yonetim.class.getName()).log(Level.SEVERE, null, ex);
             }
         }
    }//GEN-LAST:event_arama_kriteriActionPerformed

    private void txt_istenilen_programActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_istenilen_programActionPerformed
       
        try {
            // TODO add your handling code here:
            String istenen_program= txt_istenilen_program.getText();
            izlenen_program.setText(istenen_program);
            boolean dizi_mi = false;
            boolean film_mi = false;
            boolean kontrol1= false;
            String sql_sorgu;
            sql_sorgu="SELECT program_tip FROM program WHERE prog_ad ='" + istenen_program +"'";
            ResultSet myRs;
            myRs=null;
            
            myRs=Baglanti.sorgulama(sql_sorgu);
            
            while(myRs.next()){
                String kontrol = myRs.getString("program_tip");
                if(kontrol.equals("Film")){
                    film_mi=true;
                }else if(kontrol.equals("Dizi") || kontrol.equals("Tv Show")){
                    dizi_mi=true;
                }
            }
            if(film_mi==true){
                 txt_kaldigi_bolum.setText("1");
            }
            if(dizi_mi == true){
               String sql_sorgu2 = "SELECT kaldigi_bolum FROM kullanici_program WHERE program_ad ='" + istenen_program +
                       "' AND kullanici_ad ='" + kullanici + "'";
               ResultSet myRs2;
               myRs2=null;
               
               myRs2=Baglanti.sorgulama(sql_sorgu2);
               
               String kaldigi_bol_text;
               int kaldigi_bolum;
               
               while(myRs2.next()){
                   if(myRs2 != null){
                       kontrol1=true;
                   }
                       
                   if(kontrol1==true){
                   kaldigi_bol_text = myRs2.getString("kaldigi_bolum");
                   kaldigi_bolum = Integer.parseInt(kaldigi_bol_text);
                   kaldigi_bolum = kaldigi_bolum + 1;
                   kaldigi_bol_text=String.valueOf(kaldigi_bolum);
                   txt_kaldigi_bolum.setText(kaldigi_bol_text);
                   }
               }
               if(kontrol1==false){
                   txt_kaldigi_bolum.setText("1");
               }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Yonetim.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txt_istenilen_programActionPerformed

    private void aranan_turActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aranan_turActionPerformed
        try {
            // TODO add your handling code here:
            String aranan_türü=aranan_tur.getText();
            String sql_sorgu;
            sql_sorgu="SELECT prog_ad FROM program_tur WHERE prog_tur='" + aranan_türü + "'" ;
            ResultSet myRs;
            myRs = null;
            int sayac=0;
            myRs = Baglanti.sorgulama(sql_sorgu);
            while(myRs.next()){
                 Object sql_sorgusunun_cevabi;
                 sql_sorgusunun_cevabi=myRs.getString("prog_ad");
                 program_tablosu.setValueAt(sql_sorgusunun_cevabi, sayac, 0);
                 sayac++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(Yonetim.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_aranan_turActionPerformed

    private void izlebutonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izlebutonuActionPerformed
        try {
            // TODO add your handling code here:
            String kullanici1= kullanici;
            program_Adi = izlenen_program.getText();
            program_tur = null;
            
            String sql_sorgu = "SELECT prog_tur FROM program_tur WHERE prog_ad ='" + program_Adi + "'";
            ResultSet myRs;
            myRs = null;
            
            myRs = Baglanti.sorgulama(sql_sorgu);
            
            while(myRs.next()){
                program_tur=myRs.getString("prog_tur");
            }
            
           izleme_tarihi = tarih.getText();
           izleme_suresi = 15;
           
           String kaldigi_bolum =txt_kaldigi_bolum.getText();
           kaldigi_bol = Integer.parseInt(kaldigi_bolum);
           
           Puan_Degeri p = new Puan_Degeri();
           p.setVisible(true);
           
           
           
        } catch (SQLException ex) {
            Logger.getLogger(Yonetim.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_izlebutonuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Yonetim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Yonetim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Yonetim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Yonetim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Yonetim().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> arama_kriteri;
    private javax.swing.JTextField aranan_tur;
    private javax.swing.JLabel bugun_yazi;
    private javax.swing.JLabel istenilen_program;
    private javax.swing.JButton izlebutonu;
    private javax.swing.JTextField izlenen_program;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel kaldigi_bolum_yazi;
    private javax.swing.JLabel netflix_png;
    private javax.swing.JTable program_tablosu;
    private javax.swing.JLabel soru;
    private javax.swing.JTextField tarih;
    private javax.swing.JTable tur_tablosu;
    private javax.swing.JTextField txt_istenilen_program;
    private javax.swing.JTextField txt_kaldigi_bolum;
    private javax.swing.JLabel uyari;
    private javax.swing.JLabel yazi2;
    private javax.swing.JLabel yazi_hosgeldin;
    private javax.swing.JLabel yonetim_arkaplan;
    // End of variables declaration//GEN-END:variables
}
